### PR TITLE
added iterators

### PR DESCRIPTION
**Pull request by geekrelief**
I tried to combine the types for some of the iterators, but the mutating ones won't compile when combined because nim complains about the UncheckedArray not having an address when indexed.  https://forum.nim-lang.org/t/8557 If you have any thoughts on how to do this elegantly let me know.

### CODE REVIEW

**Comment by geekrelief** [comment]
@kaushalmodi Can you help take a look at why CI is failing?  I ran `nimble test` and `nimble doc` and things are good on my machine.

**Comment by kaushalmodi** [comment]
Thanks. I'll take a look over the weekend. 

> I'm running off devel, not sure if that makes a difference. Looks like it's failing on collect. My macro spits out a while loop with the last expression being a tuple, so it works with collect. At least it does in my testing.

It's likely that collect changed in devel. You can quickly try running the changes in this PR on nim playground.

**Comment by geekrelief** [comment]
Can you elaborate on how to test the PR on nim playground?  How can I import a specifc commit from github?

**Comment by kaushalmodi** [comment]
Sorry for not being clear. You just paste the whole code on the Playground and try running there.

**Comment by geekrelief** [comment]
Oh ok, I thought there was some hidden feature. :)

**Comment by geekrelief** [comment]
It works fine on playground. https://play.nim-lang.org/#ix=3DjQ but only on 1.6.0.  I guess we'll need to bump the nim version?

**Comment by geekrelief** [comment]
I added cleaned up the code for `rows/mrows` with clearer variable names and comments.  Let me know if have any suggestions.

**Comment by kaushalmodi** [comment]
The failure is at the use of `collect` in runnableExamples and tests. Looks like the features you added to this package don't themselves depend on Nim 1.6.0. 

Can you update the example to not use `collect`?

**Comment by kaushalmodi** [comment]
What you can do is remove `rows` and `mrows` from this PR (also revert the change to the minimum Nim version). Then you can take time to make the `rows` and `mrows` examples+test work with Nim 1.4.x, and submit that change in a different PR.

**Comment by geekrelief** [comment]
Ok I separated them and removed the dependency on `collect`.  Passing tests now.

**Pull request merged**
